-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 23:07:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Colegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Colegio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Colegio` (
  `id` INT NOT NULL,
  `Nombre` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `id` INT NOT NULL,
  `grado` INT NOT NULL,
  `salon` VARCHAR(2) NOT NULL,
  `Colegio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Curso_Colegio_idx` (`Colegio_id` ASC) ,
  CONSTRAINT `fk_Curso_Colegio`
    FOREIGN KEY (`Colegio_id`)
    REFERENCES `mydb`.`Colegio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Docente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Docente` (
  `id` INT NOT NULL,
  `Nombre` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura` (
  `id` INT NOT NULL,
  `Nombre` LONGTEXT NOT NULL,
  `Curso_id` INT NOT NULL,
  `Docente_idDocente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Asignatura_Curso1_idx` (`Curso_id` ASC) ,
  INDEX `fk_Asignatura_Docente1_idx` (`Docente_idDocente` ASC) ,
  CONSTRAINT `fk_Asignatura_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_Docente1`
    FOREIGN KEY (`Docente_idDocente`)
    REFERENCES `mydb`.`Docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `id` INT NOT NULL,
  `Nombre` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inscrito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inscrito` (
  `Asignatura_id` INT NOT NULL,
  `Estudiante_id` INT NOT NULL,
  PRIMARY KEY (`Asignatura_id`, `Estudiante_id`),
  INDEX `fk_Inscrito_Estudiante1_idx` (`Estudiante_id` ASC) ,
  CONSTRAINT `fk_Inscrito_Asignatura1`
    FOREIGN KEY (`Asignatura_id`)
    REFERENCES `mydb`.`Asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscrito_Estudiante1`
    FOREIGN KEY (`Estudiante_id`)
    REFERENCES `mydb`.`Estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Colegio`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Colegio` (`id`, `Nombre`) VALUES (1, 'IE LA MARIA');
INSERT INTO `mydb`.`Colegio` (`id`, `Nombre`) VALUES (2, 'SAN JUAN');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Curso`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Curso` (`id`, `grado`, `salon`, `Colegio_id`) VALUES (01, 2, '2', 1);
INSERT INTO `mydb`.`Curso` (`id`, `grado`, `salon`, `Colegio_id`) VALUES (02, 3, '1', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Docente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Docente` (`id`, `Nombre`) VALUES (1, 'LUIS');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Asignatura`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Asignatura` (`id`, `Nombre`, `Curso_id`, `Docente_idDocente`) VALUES (01, 'NATURALEZ', 1, 1);
INSERT INTO `mydb`.`Asignatura` (`id`, `Nombre`, `Curso_id`, `Docente_idDocente`) VALUES (2, 'SOCIALES', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Estudiante`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Estudiante` (`id`, `Nombre`) VALUES (1, 'EDUARDO');
INSERT INTO `mydb`.`Estudiante` (`id`, `Nombre`) VALUES (2, 'LUIS');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Inscrito`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Inscrito` (`Asignatura_id`, `Estudiante_id`) VALUES (1, 1);
INSERT INTO `mydb`.`Inscrito` (`Asignatura_id`, `Estudiante_id`) VALUES (2, 2);

COMMIT;

